# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Belladonna Reader
email: contact@pascal-martin.fr
description: A Wallabag application for Pocketbook Touch Lux ereaders.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://belladonna-reader.org" # the base hostname & protocol for your site
twitter_username: pascal_martin
github_username:  pmartin

# Build settings
markdown: kramdown
